name: deadline
description: Track your deadlines with Deadline App

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: 0.4.4
  firebase_auth: 0.16.0
  shared_preferences: ^2.0.6
  fluttertoast: 7.1.1
  firebase_database: ^3.1.6
  image_picker: ^0.6.7+22
  firebase_storage: 3.1.6

  flutter:
    sdk: flutter
  expansion_card: ^0.1.0
  flutter_easyloading: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/tool_icons/
    - assets/icons/social_icons/

  fonts:
    - family: Consolas
      fonts:
        - asset: assets/fonts/consolas_font.ttf